---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: chlunde@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: cert-manager
spec:
  secretName: acme-crt-secret
  commonName: "*.juicebot.net"
  dnsNames:
  - juicebot.net
  - '*.juicebot.net'
  - '*.int.juicebot.net'
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - juicebot.net
      - '*.juicebot.net'
      - '*.nd.juicebot.net'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
