apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: external-dns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:joCK+Ufufq8JOHMm0YGoM4bWFCE6By6YjmgoZlEViBxIEz39xASkDA==,iv:2xEk1EJxoxt2kXyL9eqx1dEOIHzyRpKHgBQ4k+zJe58=,tag:DHuyx+jnwsdNZQNy7ik1UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-03T22:21:30Z'
    mac: ENC[AES256_GCM,data:Dc9plrSLhhKM3SUnwMhLc03wn7HHsJNmGFCpihiIxGo6iDcOIuyBOVKXagU2QfHvqaZFyarttdHUMnLSBolTEmOiHJkFXok+FrYd64wElAjaEXw/ZKrq3MRBgz/uGfX8k2eYlBcULd2UGPbgJJHJVKA6y6yRAUG503s9M2okKDA=,iv:neBYU24N2ZKAFWq/uPbHcHjr+4kzqQc68gxQcVV+izs=,tag:3bXXI91M0gVLhV7dxeweTQ==,type:str]
    pgp:
    -   created_at: '2021-01-03T22:21:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zCDL2zo137AQf8D7gdDpKqDJOS4OeYnIKmZ1PLfRMiMb0fFh3GLOg0fHqn
            4f+k9IbAOpDufFX1d+G4RnvdgFzjJj6S7ZIONduq1R7es7a0Wfm19x9BR56D9Zcb
            +cZrO3yLNulXYQYBF8YJr65hZM0HIwudaUVE92FD9BjtFOb8UPYQoDhR0il4MOrl
            TIB9vVmyQhSPLEYL7HNGHCsMkbOZNXMpMGwvLsm9Hcp3QLDuFuwqY/d9G3mWN8Yj
            MdckUiJ4Zu5A162EUom4zYx9dS6ND7dyvi0v/ZWaOKUOFVQq1shmgdOM0NhGZnhb
            PPXRhPPWrFAYiQ0YsrPtvJfAhgGTpL4vcaliViD0Z9JeAYuI/EXM8YuR0g1QHFXH
            zsfJRMiUUP2cADMQKpennpuTHYEJ9EKvbx2NEDFVl5rLyFHJ7jVEnOZLtJSoDZX6
            1eQu6xFeRTMDDFdz60bKJXxdn2myesxZYU6Ptt9FZg==
            =3BY/
            -----END PGP MESSAGE-----
        fp: 42889E63D41F6057495CDF1F05984DF1D2E5D7A1
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
