apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggbro
  labels:
    app: loggbro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggbro
  template:
    metadata:
      labels:
        app: loggbro
    spec:
      containers:
      - name: loggbro
        image: ghcr.io/chlunde/loggbro:27d6023ed85c2ba6d12fa2a8fc7d53df520cb9a9
        env:
        - name: HUMIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: humio
              key: HUMIO_TOKEN
        ports:
        - containerPort: 514
