apiVersion: v1
kind: Service
metadata:
  name: syslog
spec:
  selector:
    app: loggbro
  ports:
          # - name: syslog-tcp
      #protocol: TCP
      #port: 514
      #      targetPort: 514
    - name: syslog-udp
      protocol: UDP
      port: 514
      targetPort: 514
    - name: syslog-udp-high
      protocol: UDP
      port: 31514
      targetPort: 514
  type: LoadBalancer
  loadBalancerIP: 192.168.1.201
