apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
    name: metallb

namespace: metallb-system

resources:
- metallb.yaml
- cm.yaml

images:
- name: quay.io/metallb/speaker
  newTag: v0.13.5
- name: quay.io/metallb/controller
  newTag: v0.13.5
