apiVersion: v1
kind: Pod
metadata:
  name: controller-1
  namespace: unifi
  labels:
     app: unifi
spec:
  hostNetwork: true
  containers:
  - name: unifi
    image: jacobalberty/unifi:stable-6
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /unifi
    ports:
    - containerPort: 8443
      name: https
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: unifi
